version: '3.8'

services:
  db_miniMarket:
    container_name: miniMarket
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
    image: postgres:16.2-alpine3.19