version: '3.5'

services:
  mini_market:
   container_name: mini_market
   ports:
     - "5432:5432"
   environment: 
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=admin
   image: postgres:alpine3.19