services:
  db_miniMarket:
    container_name: miniMarket
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
    image: postgres:16.2-alpine3.19
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass mypassword
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: mypassword